services:
  backend:
    build: ./backend
    container_name: inciguide-backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend/web
    container_name: inciguide-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
